/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.render.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import resources.render.types.InitializeRenderJobRequestFormatOpts;
import resources.render.types.InitializeRenderJobRequestTarget;
import resources.render.types.InitializeRenderJobRequestType;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = InitializeRenderJobRequest.Builder.class
)
public final class InitializeRenderJobRequest {
  private final Optional<Map<String, Object>> data;

  private final InitializeRenderJobRequestType type;

  private final InitializeRenderJobRequestTarget target;

  private final Optional<String> templateId;

  private final Optional<InitializeRenderJobRequestFormatOpts> formatOpts;

  private final Map<String, Object> additionalProperties;

  private InitializeRenderJobRequest(Optional<Map<String, Object>> data,
      InitializeRenderJobRequestType type, InitializeRenderJobRequestTarget target,
      Optional<String> templateId, Optional<InitializeRenderJobRequestFormatOpts> formatOpts,
      Map<String, Object> additionalProperties) {
    this.data = data;
    this.type = type;
    this.target = target;
    this.templateId = templateId;
    this.formatOpts = formatOpts;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("data")
  public Optional<Map<String, Object>> getData() {
    return data;
  }

  @JsonProperty("type")
  public InitializeRenderJobRequestType getType() {
    return type;
  }

  @JsonProperty("target")
  public InitializeRenderJobRequestTarget getTarget() {
    return target;
  }

  @JsonProperty("templateId")
  public Optional<String> getTemplateId() {
    return templateId;
  }

  @JsonProperty("formatOpts")
  public Optional<InitializeRenderJobRequestFormatOpts> getFormatOpts() {
    return formatOpts;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof InitializeRenderJobRequest && equalTo((InitializeRenderJobRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(InitializeRenderJobRequest other) {
    return data.equals(other.data) && type.equals(other.type) && target.equals(other.target) && templateId.equals(other.templateId) && formatOpts.equals(other.formatOpts);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.data, this.type, this.target, this.templateId, this.formatOpts);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static TypeStage builder() {
    return new Builder();
  }

  public interface TypeStage {
    TargetStage type(@NotNull InitializeRenderJobRequestType type);

    Builder from(InitializeRenderJobRequest other);
  }

  public interface TargetStage {
    _FinalStage target(@NotNull InitializeRenderJobRequestTarget target);
  }

  public interface _FinalStage {
    InitializeRenderJobRequest build();

    _FinalStage data(Optional<Map<String, Object>> data);

    _FinalStage data(Map<String, Object> data);

    _FinalStage templateId(Optional<String> templateId);

    _FinalStage templateId(String templateId);

    _FinalStage formatOpts(Optional<InitializeRenderJobRequestFormatOpts> formatOpts);

    _FinalStage formatOpts(InitializeRenderJobRequestFormatOpts formatOpts);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements TypeStage, TargetStage, _FinalStage {
    private InitializeRenderJobRequestType type;

    private InitializeRenderJobRequestTarget target;

    private Optional<InitializeRenderJobRequestFormatOpts> formatOpts = Optional.empty();

    private Optional<String> templateId = Optional.empty();

    private Optional<Map<String, Object>> data = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(InitializeRenderJobRequest other) {
      data(other.getData());
      type(other.getType());
      target(other.getTarget());
      templateId(other.getTemplateId());
      formatOpts(other.getFormatOpts());
      return this;
    }

    @java.lang.Override
    @JsonSetter("type")
    public TargetStage type(@NotNull InitializeRenderJobRequestType type) {
      this.type = Objects.requireNonNull(type, "type must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("target")
    public _FinalStage target(@NotNull InitializeRenderJobRequestTarget target) {
      this.target = Objects.requireNonNull(target, "target must not be null");
      return this;
    }

    @java.lang.Override
    public _FinalStage formatOpts(InitializeRenderJobRequestFormatOpts formatOpts) {
      this.formatOpts = Optional.ofNullable(formatOpts);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "formatOpts",
        nulls = Nulls.SKIP
    )
    public _FinalStage formatOpts(Optional<InitializeRenderJobRequestFormatOpts> formatOpts) {
      this.formatOpts = formatOpts;
      return this;
    }

    @java.lang.Override
    public _FinalStage templateId(String templateId) {
      this.templateId = Optional.ofNullable(templateId);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "templateId",
        nulls = Nulls.SKIP
    )
    public _FinalStage templateId(Optional<String> templateId) {
      this.templateId = templateId;
      return this;
    }

    @java.lang.Override
    public _FinalStage data(Map<String, Object> data) {
      this.data = Optional.ofNullable(data);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "data",
        nulls = Nulls.SKIP
    )
    public _FinalStage data(Optional<Map<String, Object>> data) {
      this.data = data;
      return this;
    }

    @java.lang.Override
    public InitializeRenderJobRequest build() {
      return new InitializeRenderJobRequest(data, type, target, templateId, formatOpts, additionalProperties);
    }
  }
}
