/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.tokens;

import core.ClientOptions;
import core.ObjectMappers;
import core.PogodocApiApiException;
import core.PogodocApiException;
import core.PogodocApiHttpResponse;
import core.RequestOptions;
import java.io.IOException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawTokensClient {
  protected final ClientOptions clientOptions;

  public AsyncRawTokensClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Invalidates an API token by storing it in the deleted tokens S3 bucket, preventing future use of the token for authentication.
   */
  public CompletableFuture<PogodocApiHttpResponse<Object>> deleteApiToken(String tokenId) {
    return deleteApiToken(tokenId,null);
  }

  /**
   * Invalidates an API token by storing it in the deleted tokens S3 bucket, preventing future use of the token for authentication.
   */
  public CompletableFuture<PogodocApiHttpResponse<Object>> deleteApiToken(String tokenId,
      RequestOptions requestOptions) {
    HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("api-tokens")
      .addPathSegment(tokenId)
      .build();
    Request okhttpRequest = new Request.Builder()
      .url(httpUrl)
      .method("DELETE", null)
      .headers(Headers.of(clientOptions.headers(requestOptions)))
      .addHeader("Content-Type", "application/json")
      .addHeader("Accept", "application/json")
      .build();
    OkHttpClient client = clientOptions.httpClient();
    if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
      client = clientOptions.httpClientWithTimeout(requestOptions);
    }
    CompletableFuture<PogodocApiHttpResponse<Object>> future = new CompletableFuture<>();
    client.newCall(okhttpRequest).enqueue(new Callback() {
      @Override
      public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
        try (ResponseBody responseBody = response.body()) {
          if (response.isSuccessful()) {
            future.complete(new PogodocApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), Object.class), response));
            return;
          }
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          future.completeExceptionally(new PogodocApiApiException("Error with status code " + response.code(), response.code(), ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response));
          return;
        }
        catch (IOException e) {
          future.completeExceptionally(new PogodocApiException("Network error executing HTTP request", e));
        }
      }

      @Override
      public void onFailure(@NotNull Call call, @NotNull IOException e) {
        future.completeExceptionally(new PogodocApiException("Network error executing HTTP request", e));
      }
    });
    return future;
  }
}
