/*
 * Pogodoc API
 *
 * API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentsJobIdRenderPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentsJobIdRenderPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentsJobIdRenderPostRequest
        //private DocumentsJobIdRenderPostRequest instance;

        public DocumentsJobIdRenderPostRequestTests()
        {
            // TODO uncomment below to create an instance of DocumentsJobIdRenderPostRequest
            //instance = new DocumentsJobIdRenderPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentsJobIdRenderPostRequest
        /// </summary>
        [Fact]
        public void DocumentsJobIdRenderPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentsJobIdRenderPostRequest
            //Assert.IsType<DocumentsJobIdRenderPostRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ShouldWaitForRenderCompletion'
        /// </summary>
        [Fact]
        public void ShouldWaitForRenderCompletionTest()
        {
            // TODO unit test for the property 'ShouldWaitForRenderCompletion'
        }

        /// <summary>
        /// Test the property 'UploadPresignedS3Url'
        /// </summary>
        [Fact]
        public void UploadPresignedS3UrlTest()
        {
            // TODO unit test for the property 'UploadPresignedS3Url'
        }
    }
}
