/*
 * Pogodoc API
 *
 * API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentsInitPostRequestAllOfTarget
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentsInitPostRequestAllOfTargetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentsInitPostRequestAllOfTarget
        //private DocumentsInitPostRequestAllOfTarget instance;

        public DocumentsInitPostRequestAllOfTargetTests()
        {
            // TODO uncomment below to create an instance of DocumentsInitPostRequestAllOfTarget
            //instance = new DocumentsInitPostRequestAllOfTarget();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentsInitPostRequestAllOfTarget
        /// </summary>
        [Fact]
        public void DocumentsInitPostRequestAllOfTargetInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentsInitPostRequestAllOfTarget
            //Assert.IsType<DocumentsInitPostRequestAllOfTarget>(instance);
        }
    }
}
