/*
 * Pogodoc API
 *
 * API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentsImmediateRenderPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentsImmediateRenderPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentsImmediateRenderPostRequest
        //private DocumentsImmediateRenderPostRequest instance;

        public DocumentsImmediateRenderPostRequestTests()
        {
            // TODO uncomment below to create an instance of DocumentsImmediateRenderPostRequest
            //instance = new DocumentsImmediateRenderPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentsImmediateRenderPostRequest
        /// </summary>
        [Fact]
        public void DocumentsImmediateRenderPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentsImmediateRenderPostRequest
            //Assert.IsType<DocumentsImmediateRenderPostRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }

        /// <summary>
        /// Test the property 'FormatOpts'
        /// </summary>
        [Fact]
        public void FormatOptsTest()
        {
            // TODO unit test for the property 'FormatOpts'
        }

        /// <summary>
        /// Test the property 'Template'
        /// </summary>
        [Fact]
        public void TemplateTest()
        {
            // TODO unit test for the property 'Template'
        }
    }
}
