/*
 * Pogodoc API
 *
 * API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TemplatesTemplateIdPut200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplatesTemplateIdPut200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplatesTemplateIdPut200Response
        //private TemplatesTemplateIdPut200Response instance;

        public TemplatesTemplateIdPut200ResponseTests()
        {
            // TODO uncomment below to create an instance of TemplatesTemplateIdPut200Response
            //instance = new TemplatesTemplateIdPut200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplatesTemplateIdPut200Response
        /// </summary>
        [Fact]
        public void TemplatesTemplateIdPut200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplatesTemplateIdPut200Response
            //Assert.IsType<TemplatesTemplateIdPut200Response>(instance);
        }

        /// <summary>
        /// Test the property 'NewContentId'
        /// </summary>
        [Fact]
        public void NewContentIdTest()
        {
            // TODO unit test for the property 'NewContentId'
        }
    }
}
