/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.templates.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import core.ObjectMappers;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = GeneratePresignedGetUrlResponse.Builder.class
)
public final class GeneratePresignedGetUrlResponse {
  private final String presignedUrl;

  private final Map<String, Object> additionalProperties;

  private GeneratePresignedGetUrlResponse(String presignedUrl,
      Map<String, Object> additionalProperties) {
    this.presignedUrl = presignedUrl;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Presigned URL to get the template
   */
  @JsonProperty("presignedUrl")
  public String getPresignedUrl() {
    return presignedUrl;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof GeneratePresignedGetUrlResponse && equalTo((GeneratePresignedGetUrlResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(GeneratePresignedGetUrlResponse other) {
    return presignedUrl.equals(other.presignedUrl);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.presignedUrl);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static PresignedUrlStage builder() {
    return new Builder();
  }

  public interface PresignedUrlStage {
    /**
     * Presigned URL to get the template
     */
    _FinalStage presignedUrl(@NotNull String presignedUrl);

    Builder from(GeneratePresignedGetUrlResponse other);
  }

  public interface _FinalStage {
    GeneratePresignedGetUrlResponse build();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements PresignedUrlStage, _FinalStage {
    private String presignedUrl;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(GeneratePresignedGetUrlResponse other) {
      presignedUrl(other.getPresignedUrl());
      return this;
    }

    /**
     * Presigned URL to get the template<p>Presigned URL to get the template</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("presignedUrl")
    public _FinalStage presignedUrl(@NotNull String presignedUrl) {
      this.presignedUrl = Objects.requireNonNull(presignedUrl, "presignedUrl must not be null");
      return this;
    }

    @java.lang.Override
    public GeneratePresignedGetUrlResponse build() {
      return new GeneratePresignedGetUrlResponse(presignedUrl, additionalProperties);
    }
  }
}
