/**
 * This file was auto-generated by Fern from our API Definition.
 */

package resources.documents.types;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;

public enum InitializeRenderJobResponseTarget {
  PDF("pdf"),

  HTML("html"),

  DOCX("docx"),

  XLSX("xlsx"),

  PPTX("pptx"),

  PNG("png"),

  JPG("jpg");

  private final String value;

  InitializeRenderJobResponseTarget(String value) {
    this.value = value;
  }

  @JsonValue
  @java.lang.Override
  public String toString() {
    return this.value;
  }
}
