// <auto-generated>
/*
 * Pogodoc API
 *
 * API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TemplatesTemplateIdClonePost200Response
    /// </summary>
    public partial class TemplatesTemplateIdClonePost200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplatesTemplateIdClonePost200Response" /> class.
        /// </summary>
        /// <param name="newTemplateId">newTemplateId</param>
        [JsonConstructor]
        public TemplatesTemplateIdClonePost200Response(string newTemplateId)
        {
            NewTemplateId = newTemplateId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets NewTemplateId
        /// </summary>
        [JsonPropertyName("newTemplateId")]
        public string NewTemplateId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TemplatesTemplateIdClonePost200Response {\n");
            sb.Append("  NewTemplateId: ").Append(NewTemplateId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TemplatesTemplateIdClonePost200Response" />
    /// </summary>
    public class TemplatesTemplateIdClonePost200ResponseJsonConverter : JsonConverter<TemplatesTemplateIdClonePost200Response>
    {
        /// <summary>
        /// Deserializes json to <see cref="TemplatesTemplateIdClonePost200Response" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TemplatesTemplateIdClonePost200Response Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> newTemplateId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "newTemplateId":
                            newTemplateId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!newTemplateId.IsSet)
                throw new ArgumentException("Property is required for class TemplatesTemplateIdClonePost200Response.", nameof(newTemplateId));

            if (newTemplateId.IsSet && newTemplateId.Value == null)
                throw new ArgumentNullException(nameof(newTemplateId), "Property is not nullable for class TemplatesTemplateIdClonePost200Response.");

            return new TemplatesTemplateIdClonePost200Response(newTemplateId.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="TemplatesTemplateIdClonePost200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="templatesTemplateIdClonePost200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TemplatesTemplateIdClonePost200Response templatesTemplateIdClonePost200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, templatesTemplateIdClonePost200Response, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TemplatesTemplateIdClonePost200Response" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="templatesTemplateIdClonePost200Response"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TemplatesTemplateIdClonePost200Response templatesTemplateIdClonePost200Response, JsonSerializerOptions jsonSerializerOptions)
        {
            if (templatesTemplateIdClonePost200Response.NewTemplateId == null)
                throw new ArgumentNullException(nameof(templatesTemplateIdClonePost200Response.NewTemplateId), "Property is required for class TemplatesTemplateIdClonePost200Response.");

            writer.WriteString("newTemplateId", templatesTemplateIdClonePost200Response.NewTemplateId);
        }
    }
}
