/*
 * Pogodoc API
 * API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.client.model.DocumentsInitPostRequestAllOfTarget;
import org.openapitools.client.model.TemplatesTemplateIdPutRequestAllOfTemplateInfoType;
import org.openapitools.client.model.TemplatesTemplateIdRenderPreviewsPostRequestFormatOpts;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DocumentsInitPostRequest
 */
public class DocumentsInitPostRequestTest {
    private final DocumentsInitPostRequest model = new DocumentsInitPostRequest();

    /**
     * Model tests for DocumentsInitPostRequest
     */
    @Test
    public void testDocumentsInitPostRequest() {
        // TODO: test DocumentsInitPostRequest
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'target'
     */
    @Test
    public void targetTest() {
        // TODO: test target
    }

    /**
     * Test the property 'templateId'
     */
    @Test
    public void templateIdTest() {
        // TODO: test templateId
    }

    /**
     * Test the property 'formatOpts'
     */
    @Test
    public void formatOptsTest() {
        // TODO: test formatOpts
    }

}
