/*
 * Pogodoc API
 * API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TemplatesTemplateIdPutRequestAllOfPreviewIds
 */
public class TemplatesTemplateIdPutRequestAllOfPreviewIdsTest {
    private final TemplatesTemplateIdPutRequestAllOfPreviewIds model = new TemplatesTemplateIdPutRequestAllOfPreviewIds();

    /**
     * Model tests for TemplatesTemplateIdPutRequestAllOfPreviewIds
     */
    @Test
    public void testTemplatesTemplateIdPutRequestAllOfPreviewIds() {
        // TODO: test TemplatesTemplateIdPutRequestAllOfPreviewIds
    }

    /**
     * Test the property 'pngJobId'
     */
    @Test
    public void pngJobIdTest() {
        // TODO: test pngJobId
    }

    /**
     * Test the property 'pdfJobId'
     */
    @Test
    public void pdfJobIdTest() {
        // TODO: test pdfJobId
    }

}
