/*
 * Pogodoc API
 * API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TemplatesTemplateIdPutRequestAllOfPreviewIds
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-02T10:51:10.425208+02:00[Europe/Skopje]", comments = "Generator version: 7.13.0")
public class TemplatesTemplateIdPutRequestAllOfPreviewIds {
  public static final String SERIALIZED_NAME_PNG_JOB_ID = "pngJobId";
  @SerializedName(SERIALIZED_NAME_PNG_JOB_ID)
  @javax.annotation.Nonnull
  private String pngJobId;

  public static final String SERIALIZED_NAME_PDF_JOB_ID = "pdfJobId";
  @SerializedName(SERIALIZED_NAME_PDF_JOB_ID)
  @javax.annotation.Nonnull
  private String pdfJobId;

  public TemplatesTemplateIdPutRequestAllOfPreviewIds() {
  }

  public TemplatesTemplateIdPutRequestAllOfPreviewIds pngJobId(@javax.annotation.Nonnull String pngJobId) {
    this.pngJobId = pngJobId;
    return this;
  }

  /**
   * Get pngJobId
   * @return pngJobId
   */
  @javax.annotation.Nonnull
  public String getPngJobId() {
    return pngJobId;
  }

  public void setPngJobId(@javax.annotation.Nonnull String pngJobId) {
    this.pngJobId = pngJobId;
  }


  public TemplatesTemplateIdPutRequestAllOfPreviewIds pdfJobId(@javax.annotation.Nonnull String pdfJobId) {
    this.pdfJobId = pdfJobId;
    return this;
  }

  /**
   * Get pdfJobId
   * @return pdfJobId
   */
  @javax.annotation.Nonnull
  public String getPdfJobId() {
    return pdfJobId;
  }

  public void setPdfJobId(@javax.annotation.Nonnull String pdfJobId) {
    this.pdfJobId = pdfJobId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplatesTemplateIdPutRequestAllOfPreviewIds templatesTemplateIdPutRequestAllOfPreviewIds = (TemplatesTemplateIdPutRequestAllOfPreviewIds) o;
    return Objects.equals(this.pngJobId, templatesTemplateIdPutRequestAllOfPreviewIds.pngJobId) &&
        Objects.equals(this.pdfJobId, templatesTemplateIdPutRequestAllOfPreviewIds.pdfJobId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pngJobId, pdfJobId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplatesTemplateIdPutRequestAllOfPreviewIds {\n");
    sb.append("    pngJobId: ").append(toIndentedString(pngJobId)).append("\n");
    sb.append("    pdfJobId: ").append(toIndentedString(pdfJobId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("pngJobId");
    openapiFields.add("pdfJobId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("pngJobId");
    openapiRequiredFields.add("pdfJobId");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TemplatesTemplateIdPutRequestAllOfPreviewIds
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TemplatesTemplateIdPutRequestAllOfPreviewIds.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TemplatesTemplateIdPutRequestAllOfPreviewIds is not found in the empty JSON string", TemplatesTemplateIdPutRequestAllOfPreviewIds.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TemplatesTemplateIdPutRequestAllOfPreviewIds.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TemplatesTemplateIdPutRequestAllOfPreviewIds` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TemplatesTemplateIdPutRequestAllOfPreviewIds.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("pngJobId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pngJobId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pngJobId").toString()));
      }
      if (!jsonObj.get("pdfJobId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pdfJobId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pdfJobId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TemplatesTemplateIdPutRequestAllOfPreviewIds.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TemplatesTemplateIdPutRequestAllOfPreviewIds' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TemplatesTemplateIdPutRequestAllOfPreviewIds> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TemplatesTemplateIdPutRequestAllOfPreviewIds.class));

       return (TypeAdapter<T>) new TypeAdapter<TemplatesTemplateIdPutRequestAllOfPreviewIds>() {
           @Override
           public void write(JsonWriter out, TemplatesTemplateIdPutRequestAllOfPreviewIds value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TemplatesTemplateIdPutRequestAllOfPreviewIds read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TemplatesTemplateIdPutRequestAllOfPreviewIds given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TemplatesTemplateIdPutRequestAllOfPreviewIds
   * @throws IOException if the JSON string is invalid with respect to TemplatesTemplateIdPutRequestAllOfPreviewIds
   */
  public static TemplatesTemplateIdPutRequestAllOfPreviewIds fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TemplatesTemplateIdPutRequestAllOfPreviewIds.class);
  }

  /**
   * Convert an instance of TemplatesTemplateIdPutRequestAllOfPreviewIds to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

