/*
 * Pogodoc API
 * API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TemplatesTemplateIdClonePost200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-02T10:51:10.425208+02:00[Europe/Skopje]", comments = "Generator version: 7.13.0")
public class TemplatesTemplateIdClonePost200Response {
  public static final String SERIALIZED_NAME_NEW_TEMPLATE_ID = "newTemplateId";
  @SerializedName(SERIALIZED_NAME_NEW_TEMPLATE_ID)
  @javax.annotation.Nonnull
  private String newTemplateId;

  public TemplatesTemplateIdClonePost200Response() {
  }

  public TemplatesTemplateIdClonePost200Response newTemplateId(@javax.annotation.Nonnull String newTemplateId) {
    this.newTemplateId = newTemplateId;
    return this;
  }

  /**
   * Get newTemplateId
   * @return newTemplateId
   */
  @javax.annotation.Nonnull
  public String getNewTemplateId() {
    return newTemplateId;
  }

  public void setNewTemplateId(@javax.annotation.Nonnull String newTemplateId) {
    this.newTemplateId = newTemplateId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemplatesTemplateIdClonePost200Response templatesTemplateIdClonePost200Response = (TemplatesTemplateIdClonePost200Response) o;
    return Objects.equals(this.newTemplateId, templatesTemplateIdClonePost200Response.newTemplateId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newTemplateId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemplatesTemplateIdClonePost200Response {\n");
    sb.append("    newTemplateId: ").append(toIndentedString(newTemplateId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("newTemplateId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("newTemplateId");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TemplatesTemplateIdClonePost200Response
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TemplatesTemplateIdClonePost200Response.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TemplatesTemplateIdClonePost200Response is not found in the empty JSON string", TemplatesTemplateIdClonePost200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TemplatesTemplateIdClonePost200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TemplatesTemplateIdClonePost200Response` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TemplatesTemplateIdClonePost200Response.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("newTemplateId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `newTemplateId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("newTemplateId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TemplatesTemplateIdClonePost200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TemplatesTemplateIdClonePost200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TemplatesTemplateIdClonePost200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TemplatesTemplateIdClonePost200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<TemplatesTemplateIdClonePost200Response>() {
           @Override
           public void write(JsonWriter out, TemplatesTemplateIdClonePost200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TemplatesTemplateIdClonePost200Response read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TemplatesTemplateIdClonePost200Response given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TemplatesTemplateIdClonePost200Response
   * @throws IOException if the JSON string is invalid with respect to TemplatesTemplateIdClonePost200Response
   */
  public static TemplatesTemplateIdClonePost200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TemplatesTemplateIdClonePost200Response.class);
  }

  /**
   * Convert an instance of TemplatesTemplateIdClonePost200Response to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

