/**
 * This file was auto-generated by Fern from our API Definition.
 */

import core.ClientOptions;
import core.Suppliers;
import java.util.function.Supplier;
import resources.documents.AsyncDocumentsClient;
import resources.templates.AsyncTemplatesClient;

public class AsyncPogodocApiClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<AsyncTemplatesClient> templatesClient;

  protected final Supplier<AsyncDocumentsClient> documentsClient;

  public AsyncPogodocApiClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.templatesClient = Suppliers.memoize(() -> new AsyncTemplatesClient(clientOptions));
    this.documentsClient = Suppliers.memoize(() -> new AsyncDocumentsClient(clientOptions));
  }

  public AsyncTemplatesClient templates() {
    return this.templatesClient.get();
  }

  public AsyncDocumentsClient documents() {
    return this.documentsClient.get();
  }

  public static AsyncPogodocApiClientBuilder builder() {
    return new AsyncPogodocApiClientBuilder();
  }
}
