// This file was auto-generated by Fern from our API Definition.

package client

import (
	core "github.com/Pogodoc/pogodoc-go/client/core"
	documents "github.com/Pogodoc/pogodoc-go/client/documents"
	internal "github.com/Pogodoc/pogodoc-go/client/internal"
	option "github.com/Pogodoc/pogodoc-go/client/option"
	templates "github.com/Pogodoc/pogodoc-go/client/templates"
	http "net/http"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Templates *templates.Client
	Documents *documents.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:    options.ToHeader(),
		Templates: templates.NewClient(opts...),
		Documents: documents.NewClient(opts...),
	}
}
