# This file was auto-generated by Fern from our API Definition.

import typing

GenerateTemplatePreviewsRequestFormatOptsOrientation = typing.Union[typing.Literal["landscape", "portrait"], typing.Any]
