# This file was auto-generated by Fern from our API Definition.

import typing

GetTemplateByIdResponseType = typing.Union[
    typing.Literal["docx", "xlsx", "pptx", "ejs", "html", "latex", "framework"], typing.Any
]
