# This file was auto-generated by Fern from our API Definition.

import typing

GetUserTemplatesRequestSort = typing.Union[
    typing.Literal["createdAt:desc", "createdAt:asc", "updatedAt:desc", "updatedAt:asc", "title:asc", "title:desc"],
    typing.Any,
]
