# This file was auto-generated by Fern from our API Definition.

import typing

GetUserTemplatesRequestCategory = typing.Union[
    typing.Literal[
        "invoice",
        "mail",
        "report",
        "cv",
        "receipt",
        "order",
        "contract",
        "certificate",
        "statement",
        "brochure",
        "warranty",
        "poster",
        "menu",
        "catalog",
        "packaging",
        "advertisement",
        "other",
        "favorite",
    ],
    typing.Any,
]
