# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .get_template_by_id_response_permissions import GetTemplateByIdResponsePermissions
from .get_template_by_id_response_type import GetTemplateByIdResponseType


class GetTemplateByIdResponse(UniversalBaseModel):
    uuid_: typing_extensions.Annotated[str, FieldMetadata(alias="uuid")] = pydantic.Field()
    """
    Unique ID of the template
    """

    title: str = pydantic.Field()
    """
    Title of the template
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description of the template
    """

    type: GetTemplateByIdResponseType = pydantic.Field()
    """
    Type of template to be rendered
    """

    categories: typing.List[str] = pydantic.Field()
    """
    Categories of the template
    """

    permissions: GetTemplateByIdResponsePermissions = pydantic.Field()
    """
    Permissions of the template
    """

    preview: typing.Optional[str] = pydantic.Field(default=None)
    """
    Preview URL of the template
    """

    content_id: typing_extensions.Annotated[str, FieldMetadata(alias="contentId")] = pydantic.Field()
    """
    Content ID of the template in S3
    """

    source_code: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="sourceCode")] = pydantic.Field(
        default=None
    )
    """
    Source code of the template
    """

    sample_data: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]], FieldMetadata(alias="sampleData")
    ] = pydantic.Field(default=None)
    """
    Sample data for the template
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
