<?php
/**
 * TemplatesApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Pogodoc API
 *
 * API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TemplatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TemplatesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for templatesInitGet
     *
     * Initialize Template Creation.
     *
     */
    public function testTemplatesInitGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templatesTemplateIdClonePost
     *
     * Clone Template.
     *
     */
    public function testTemplatesTemplateIdClonePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templatesTemplateIdDelete
     *
     * Delete Template.
     *
     */
    public function testTemplatesTemplateIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templatesTemplateIdIndexHtmlGet
     *
     * Get Template Index HTML.
     *
     */
    public function testTemplatesTemplateIdIndexHtmlGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templatesTemplateIdIndexHtmlPost
     *
     * Upload Template Index HTML.
     *
     */
    public function testTemplatesTemplateIdIndexHtmlPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templatesTemplateIdPost
     *
     * Save New Template.
     *
     */
    public function testTemplatesTemplateIdPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templatesTemplateIdPresignedUrlGet
     *
     * Generate Presigned URL.
     *
     */
    public function testTemplatesTemplateIdPresignedUrlGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templatesTemplateIdPut
     *
     * Update Template.
     *
     */
    public function testTemplatesTemplateIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templatesTemplateIdRenderPreviewsPost
     *
     * Generate Template Previews.
     *
     */
    public function testTemplatesTemplateIdRenderPreviewsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templatesTemplateIdUnzipPost
     *
     * Extract Template Files.
     *
     */
    public function testTemplatesTemplateIdUnzipPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
