/**
 * This file was auto-generated by Fern from our API Definition.
 */

package core;

import java.lang.Exception;
import java.lang.RuntimeException;
import java.lang.String;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class PogodocApiException extends RuntimeException {
  public PogodocApiException(String message) {
    super(message);
  }

  public PogodocApiException(String message, Exception e) {
    super(message, e);
  }
}
