# coding: utf-8

"""
    Pogodoc API

    API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.documents_init_post200_response import DocumentsInitPost200Response

class TestDocumentsInitPost200Response(unittest.TestCase):
    """DocumentsInitPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentsInitPost200Response:
        """Test DocumentsInitPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentsInitPost200Response`
        """
        model = DocumentsInitPost200Response()
        if include_optional:
            return DocumentsInitPost200Response(
                job_id = '',
                target = None,
                presigned_data_upload_url = '',
                presigned_template_upload_url = ''
            )
        else:
            return DocumentsInitPost200Response(
                job_id = '',
                target = None,
                presigned_data_upload_url = '',
                presigned_template_upload_url = '',
        )
        """

    def testDocumentsInitPost200Response(self):
        """Test DocumentsInitPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
