# coding: utf-8

"""
    Pogodoc API

    API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.templates_template_id_clone_post200_response import TemplatesTemplateIdClonePost200Response

class TestTemplatesTemplateIdClonePost200Response(unittest.TestCase):
    """TemplatesTemplateIdClonePost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatesTemplateIdClonePost200Response:
        """Test TemplatesTemplateIdClonePost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatesTemplateIdClonePost200Response`
        """
        model = TemplatesTemplateIdClonePost200Response()
        if include_optional:
            return TemplatesTemplateIdClonePost200Response(
                new_template_id = ''
            )
        else:
            return TemplatesTemplateIdClonePost200Response(
                new_template_id = '',
        )
        """

    def testTemplatesTemplateIdClonePost200Response(self):
        """Test TemplatesTemplateIdClonePost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
