# coding: utf-8

"""
    Pogodoc API

    API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.templates_template_id_render_previews_post200_response_png_preview import TemplatesTemplateIdRenderPreviewsPost200ResponsePngPreview

class TestTemplatesTemplateIdRenderPreviewsPost200ResponsePngPreview(unittest.TestCase):
    """TemplatesTemplateIdRenderPreviewsPost200ResponsePngPreview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatesTemplateIdRenderPreviewsPost200ResponsePngPreview:
        """Test TemplatesTemplateIdRenderPreviewsPost200ResponsePngPreview
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatesTemplateIdRenderPreviewsPost200ResponsePngPreview`
        """
        model = TemplatesTemplateIdRenderPreviewsPost200ResponsePngPreview()
        if include_optional:
            return TemplatesTemplateIdRenderPreviewsPost200ResponsePngPreview(
                url = '',
                job_id = ''
            )
        else:
            return TemplatesTemplateIdRenderPreviewsPost200ResponsePngPreview(
                job_id = '',
        )
        """

    def testTemplatesTemplateIdRenderPreviewsPost200ResponsePngPreview(self):
        """Test TemplatesTemplateIdRenderPreviewsPost200ResponsePngPreview"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
