/**
 * This file was auto-generated by Fern from our API Definition.
 */

import core.ClientOptions;
import core.Suppliers;
import java.util.function.Supplier;
import resources.render.AsyncRenderClient;
import resources.templates.AsyncTemplatesClient;
import resources.tokens.AsyncTokensClient;

public class AsyncPogodocApiClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<AsyncTemplatesClient> templatesClient;

  protected final Supplier<AsyncRenderClient> renderClient;

  protected final Supplier<AsyncTokensClient> tokensClient;

  public AsyncPogodocApiClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.templatesClient = Suppliers.memoize(() -> new AsyncTemplatesClient(clientOptions));
    this.renderClient = Suppliers.memoize(() -> new AsyncRenderClient(clientOptions));
    this.tokensClient = Suppliers.memoize(() -> new AsyncTokensClient(clientOptions));
  }

  public AsyncTemplatesClient templates() {
    return this.templatesClient.get();
  }

  public AsyncRenderClient render() {
    return this.renderClient.get();
  }

  public AsyncTokensClient tokens() {
    return this.tokensClient.get();
  }

  public static AsyncPogodocApiClientBuilder builder() {
    return new AsyncPogodocApiClientBuilder();
  }
}
