/**
 * This file was auto-generated by Fern from our API Definition.
 */

import core.ClientOptions;
import core.Suppliers;
import java.util.function.Supplier;
import resources.render.RenderClient;
import resources.templates.TemplatesClient;
import resources.tokens.TokensClient;

public class PogodocApiClient {
  protected final ClientOptions clientOptions;

  protected final Supplier<TemplatesClient> templatesClient;

  protected final Supplier<RenderClient> renderClient;

  protected final Supplier<TokensClient> tokensClient;

  public PogodocApiClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.templatesClient = Suppliers.memoize(() -> new TemplatesClient(clientOptions));
    this.renderClient = Suppliers.memoize(() -> new RenderClient(clientOptions));
    this.tokensClient = Suppliers.memoize(() -> new TokensClient(clientOptions));
  }

  public TemplatesClient templates() {
    return this.templatesClient.get();
  }

  public RenderClient render() {
    return this.renderClient.get();
  }

  public TokensClient tokens() {
    return this.tokensClient.get();
  }

  public static PogodocApiClientBuilder builder() {
    return new PogodocApiClientBuilder();
  }
}
