// <auto-generated>
/*
 * Pogodoc API
 *
 * API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using Org.OpenAPITools.Client;
using System.Diagnostics.CodeAnalysis;

namespace Org.OpenAPITools.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface ITokensApi : IApi
    {
        /// <summary>
        /// The class containing the events
        /// </summary>
        TokensApiEvents Events { get; }

        /// <summary>
        /// Delete API Token
        /// </summary>
        /// <remarks>
        /// Invalidates an API token by storing it in the deleted tokens S3 bucket, preventing future use of the token for authentication.
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="tokenId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiTokensTokenIdDeleteApiResponse"/>&gt;</returns>
        Task<IApiTokensTokenIdDeleteApiResponse> ApiTokensTokenIdDeleteAsync(string tokenId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete API Token
        /// </summary>
        /// <remarks>
        /// Invalidates an API token by storing it in the deleted tokens S3 bucket, preventing future use of the token for authentication.
        /// </remarks>
        /// <param name="tokenId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiTokensTokenIdDeleteApiResponse"/>?&gt;</returns>
        Task<IApiTokensTokenIdDeleteApiResponse?> ApiTokensTokenIdDeleteOrDefaultAsync(string tokenId, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IApiTokensTokenIdDeleteApiResponse"/>
    /// </summary>
    public interface IApiTokensTokenIdDeleteApiResponse : Org.OpenAPITools.Client.IApiResponse, IOk<Object?>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class TokensApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs>? OnApiTokensTokenIdDelete;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs>? OnErrorApiTokensTokenIdDelete;

        internal void ExecuteOnApiTokensTokenIdDelete(TokensApi.ApiTokensTokenIdDeleteApiResponse apiResponse)
        {
            OnApiTokensTokenIdDelete?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorApiTokensTokenIdDelete(Exception exception)
        {
            OnErrorApiTokensTokenIdDelete?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class TokensApi : ITokensApi
    {
        private JsonSerializerOptions _jsonSerializerOptions;

        /// <summary>
        /// The logger factory
        /// </summary>
        public ILoggerFactory LoggerFactory { get; }

        /// <summary>
        /// The logger
        /// </summary>
        public ILogger<TokensApi> Logger { get; }

        /// <summary>
        /// The HttpClient
        /// </summary>
        public HttpClient HttpClient { get; }

        /// <summary>
        /// The class containing the events
        /// </summary>
        public TokensApiEvents Events { get; }

        /// <summary>
        /// A token provider of type <see cref="BearerToken"/>
        /// </summary>
        public TokenProvider<BearerToken> BearerTokenProvider { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="TokensApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TokensApi(ILogger<TokensApi> logger, ILoggerFactory loggerFactory, HttpClient httpClient, JsonSerializerOptionsProvider jsonSerializerOptionsProvider, TokensApiEvents tokensApiEvents,
            TokenProvider<BearerToken> bearerTokenProvider)
        {
            _jsonSerializerOptions = jsonSerializerOptionsProvider.Options;
            LoggerFactory = loggerFactory;
            Logger = LoggerFactory.CreateLogger<TokensApi>();
            HttpClient = httpClient;
            Events = tokensApiEvents;
            BearerTokenProvider = bearerTokenProvider;
        }

        partial void FormatApiTokensTokenIdDelete(ref string tokenId);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="tokenId"></param>
        /// <returns></returns>
        private void ValidateApiTokensTokenIdDelete(string tokenId)
        {
            if (tokenId == null)
                throw new ArgumentNullException(nameof(tokenId));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="tokenId"></param>
        private void AfterApiTokensTokenIdDeleteDefaultImplementation(IApiTokensTokenIdDeleteApiResponse apiResponseLocalVar, string tokenId)
        {
            bool suppressDefaultLog = false;
            AfterApiTokensTokenIdDelete(ref suppressDefaultLog, apiResponseLocalVar, tokenId);
            if (!suppressDefaultLog)
                Logger.LogInformation("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="tokenId"></param>
        partial void AfterApiTokensTokenIdDelete(ref bool suppressDefaultLog, IApiTokensTokenIdDeleteApiResponse apiResponseLocalVar, string tokenId);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="tokenId"></param>
        private void OnErrorApiTokensTokenIdDeleteDefaultImplementation(Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string tokenId)
        {
            bool suppressDefaultLogLocalVar = false;
            OnErrorApiTokensTokenIdDelete(ref suppressDefaultLogLocalVar, exceptionLocalVar, pathFormatLocalVar, pathLocalVar, tokenId);
            if (!suppressDefaultLogLocalVar)
                Logger.LogError(exceptionLocalVar, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLogLocalVar"></param>
        /// <param name="exceptionLocalVar"></param>
        /// <param name="pathFormatLocalVar"></param>
        /// <param name="pathLocalVar"></param>
        /// <param name="tokenId"></param>
        partial void OnErrorApiTokensTokenIdDelete(ref bool suppressDefaultLogLocalVar, Exception exceptionLocalVar, string pathFormatLocalVar, string pathLocalVar, string tokenId);

        /// <summary>
        /// Delete API Token Invalidates an API token by storing it in the deleted tokens S3 bucket, preventing future use of the token for authentication.
        /// </summary>
        /// <param name="tokenId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiTokensTokenIdDeleteApiResponse"/>&gt;</returns>
        public async Task<IApiTokensTokenIdDeleteApiResponse?> ApiTokensTokenIdDeleteOrDefaultAsync(string tokenId, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await ApiTokensTokenIdDeleteAsync(tokenId, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        /// Delete API Token Invalidates an API token by storing it in the deleted tokens S3 bucket, preventing future use of the token for authentication.
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="tokenId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IApiTokensTokenIdDeleteApiResponse"/>&gt;</returns>
        public async Task<IApiTokensTokenIdDeleteApiResponse> ApiTokensTokenIdDeleteAsync(string tokenId, System.Threading.CancellationToken cancellationToken = default)
        {
            UriBuilder uriBuilderLocalVar = new UriBuilder();

            try
            {
                ValidateApiTokensTokenIdDelete(tokenId);

                FormatApiTokensTokenIdDelete(ref tokenId);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    uriBuilderLocalVar.Host = HttpClient.BaseAddress!.Host;
                    uriBuilderLocalVar.Port = HttpClient.BaseAddress.Port;
                    uriBuilderLocalVar.Scheme = HttpClient.BaseAddress.Scheme;
                    uriBuilderLocalVar.Path = HttpClient.BaseAddress.AbsolutePath == "/"
                        ? "/api-tokens/{tokenId}"
                        : string.Concat(HttpClient.BaseAddress.AbsolutePath, "/api-tokens/{tokenId}");
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7BtokenId%7D", Uri.EscapeDataString(tokenId.ToString()));

                    List<TokenBase> tokenBaseLocalVars = new List<TokenBase>();
                    httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;

                    BearerToken bearerTokenLocalVar1 = (BearerToken) await BearerTokenProvider.GetAsync(cancellation: cancellationToken).ConfigureAwait(false);

                    tokenBaseLocalVars.Add(bearerTokenLocalVar1);

                    bearerTokenLocalVar1.UseInHeader(httpRequestMessageLocalVar, "");

                    string[] acceptLocalVars = new string[] {
                        "application/json"
                    };

                    string? acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Delete;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await HttpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                        ILogger<ApiTokensTokenIdDeleteApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<ApiTokensTokenIdDeleteApiResponse>();

                        ApiTokensTokenIdDeleteApiResponse apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api-tokens/{tokenId}", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterApiTokensTokenIdDeleteDefaultImplementation(apiResponseLocalVar, tokenId);

                        Events.ExecuteOnApiTokensTokenIdDelete(apiResponseLocalVar);

                        if (apiResponseLocalVar.StatusCode == (HttpStatusCode) 429)
                            foreach(TokenBase tokenBaseLocalVar in tokenBaseLocalVars)
                                tokenBaseLocalVar.BeginRateLimit();

                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorApiTokensTokenIdDeleteDefaultImplementation(e, "/api-tokens/{tokenId}", uriBuilderLocalVar.Path, tokenId);
                Events.ExecuteOnErrorApiTokensTokenIdDelete(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="ApiTokensTokenIdDeleteApiResponse"/>
        /// </summary>
        public partial class ApiTokensTokenIdDeleteApiResponse : Org.OpenAPITools.Client.ApiResponse, IApiTokensTokenIdDeleteApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<ApiTokensTokenIdDeleteApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="ApiTokensTokenIdDeleteApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public ApiTokensTokenIdDeleteApiResponse(ILogger<ApiTokensTokenIdDeleteApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public Object? Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<Object>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out Object? result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}
