=begin
#Pogodoc API

#API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.

The version of the OpenAPI document: 0.1.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::TemplatesTemplateIdPutRequestAllOfPreviewIds
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::TemplatesTemplateIdPutRequestAllOfPreviewIds do
  let(:instance) { OpenapiClient::TemplatesTemplateIdPutRequestAllOfPreviewIds.new }

  describe 'test an instance of TemplatesTemplateIdPutRequestAllOfPreviewIds' do
    it 'should create an instance of TemplatesTemplateIdPutRequestAllOfPreviewIds' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::TemplatesTemplateIdPutRequestAllOfPreviewIds)
    end
  end

  describe 'test attribute "png_job_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "pdf_job_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
