// This file was auto-generated by Fern from our API Definition.

package client

import (
	http "net/http"
	core "pogodoc/go/sdk/core"
	documents "pogodoc/go/sdk/documents"
	internal "pogodoc/go/sdk/internal"
	option "pogodoc/go/sdk/option"
	templates "pogodoc/go/sdk/templates"
	tokens "pogodoc/go/sdk/tokens"
)

type Client struct {
	baseURL string
	caller  *internal.Caller
	header  http.Header

	Templates *templates.Client
	Documents *documents.Client
	Tokens    *tokens.Client
}

func NewClient(opts ...option.RequestOption) *Client {
	options := core.NewRequestOptions(opts...)
	return &Client{
		baseURL: options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
		header:    options.ToHeader(),
		Templates: templates.NewClient(opts...),
		Documents: documents.NewClient(opts...),
		Tokens:    tokens.NewClient(opts...),
	}
}
