# coding: utf-8

"""
    Pogodoc API

    API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.documents_init_post_request_all_of_target import DocumentsInitPostRequestAllOfTarget
from typing import Optional, Set
from typing_extensions import Self

class DocumentsInitPost200Response(BaseModel):
    """
    DocumentsInitPost200Response
    """ # noqa: E501
    job_id: StrictStr = Field(alias="jobId")
    target: DocumentsInitPostRequestAllOfTarget
    presigned_data_upload_url: Optional[StrictStr] = Field(alias="presignedDataUploadUrl")
    presigned_template_upload_url: Optional[StrictStr] = Field(alias="presignedTemplateUploadUrl")
    __properties: ClassVar[List[str]] = ["jobId", "target", "presignedDataUploadUrl", "presignedTemplateUploadUrl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentsInitPost200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of target
        if self.target:
            _dict['target'] = self.target.to_dict()
        # set to None if presigned_data_upload_url (nullable) is None
        # and model_fields_set contains the field
        if self.presigned_data_upload_url is None and "presigned_data_upload_url" in self.model_fields_set:
            _dict['presignedDataUploadUrl'] = None

        # set to None if presigned_template_upload_url (nullable) is None
        # and model_fields_set contains the field
        if self.presigned_template_upload_url is None and "presigned_template_upload_url" in self.model_fields_set:
            _dict['presignedTemplateUploadUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentsInitPost200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "jobId": obj.get("jobId"),
            "target": DocumentsInitPostRequestAllOfTarget.from_dict(obj["target"]) if obj.get("target") is not None else None,
            "presignedDataUploadUrl": obj.get("presignedDataUploadUrl"),
            "presignedTemplateUploadUrl": obj.get("presignedTemplateUploadUrl")
        })
        return _obj


