# coding: utf-8

"""
    Pogodoc API

    API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.templates_template_id_put_request_all_of_template_info_categories_inner import TemplatesTemplateIdPutRequestAllOfTemplateInfoCategoriesInner
from openapi_client.models.templates_template_id_put_request_all_of_template_info_type import TemplatesTemplateIdPutRequestAllOfTemplateInfoType
from typing import Optional, Set
from typing_extensions import Self

class TemplatesTemplateIdPutRequestAllOfTemplateInfo(BaseModel):
    """
    TemplatesTemplateIdPutRequestAllOfTemplateInfo
    """ # noqa: E501
    title: StrictStr
    description: StrictStr
    type: TemplatesTemplateIdPutRequestAllOfTemplateInfoType
    sample_data: Dict[str, Any] = Field(alias="sampleData")
    source_code: Optional[StrictStr] = Field(default=None, alias="sourceCode")
    categories: List[TemplatesTemplateIdPutRequestAllOfTemplateInfoCategoriesInner]
    __properties: ClassVar[List[str]] = ["title", "description", "type", "sampleData", "sourceCode", "categories"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TemplatesTemplateIdPutRequestAllOfTemplateInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of type
        if self.type:
            _dict['type'] = self.type.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in categories (list)
        _items = []
        if self.categories:
            for _item_categories in self.categories:
                if _item_categories:
                    _items.append(_item_categories.to_dict())
            _dict['categories'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TemplatesTemplateIdPutRequestAllOfTemplateInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "description": obj.get("description"),
            "type": TemplatesTemplateIdPutRequestAllOfTemplateInfoType.from_dict(obj["type"]) if obj.get("type") is not None else None,
            "sampleData": obj.get("sampleData"),
            "sourceCode": obj.get("sourceCode"),
            "categories": [TemplatesTemplateIdPutRequestAllOfTemplateInfoCategoriesInner.from_dict(_item) for _item in obj["categories"]] if obj.get("categories") is not None else None
        })
        return _obj


