/*
Pogodoc API

API for Pogodoc document and template management service. Provides endpoints for rendering documents, managing templates, generating previews, and handling API tokens.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DocumentsJobIdRenderPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentsJobIdRenderPost200Response{}

// DocumentsJobIdRenderPost200Response struct for DocumentsJobIdRenderPost200Response
type DocumentsJobIdRenderPost200Response struct {
	JobId string `json:"jobId"`
}

type _DocumentsJobIdRenderPost200Response DocumentsJobIdRenderPost200Response

// NewDocumentsJobIdRenderPost200Response instantiates a new DocumentsJobIdRenderPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentsJobIdRenderPost200Response(jobId string) *DocumentsJobIdRenderPost200Response {
	this := DocumentsJobIdRenderPost200Response{}
	this.JobId = jobId
	return &this
}

// NewDocumentsJobIdRenderPost200ResponseWithDefaults instantiates a new DocumentsJobIdRenderPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentsJobIdRenderPost200ResponseWithDefaults() *DocumentsJobIdRenderPost200Response {
	this := DocumentsJobIdRenderPost200Response{}
	return &this
}

// GetJobId returns the JobId field value
func (o *DocumentsJobIdRenderPost200Response) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *DocumentsJobIdRenderPost200Response) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *DocumentsJobIdRenderPost200Response) SetJobId(v string) {
	o.JobId = v
}

func (o DocumentsJobIdRenderPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentsJobIdRenderPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobId"] = o.JobId
	return toSerialize, nil
}

func (o *DocumentsJobIdRenderPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocumentsJobIdRenderPost200Response := _DocumentsJobIdRenderPost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocumentsJobIdRenderPost200Response)

	if err != nil {
		return err
	}

	*o = DocumentsJobIdRenderPost200Response(varDocumentsJobIdRenderPost200Response)

	return err
}

type NullableDocumentsJobIdRenderPost200Response struct {
	value *DocumentsJobIdRenderPost200Response
	isSet bool
}

func (v NullableDocumentsJobIdRenderPost200Response) Get() *DocumentsJobIdRenderPost200Response {
	return v.value
}

func (v *NullableDocumentsJobIdRenderPost200Response) Set(val *DocumentsJobIdRenderPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentsJobIdRenderPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentsJobIdRenderPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentsJobIdRenderPost200Response(val *DocumentsJobIdRenderPost200Response) *NullableDocumentsJobIdRenderPost200Response {
	return &NullableDocumentsJobIdRenderPost200Response{value: val, isSet: true}
}

func (v NullableDocumentsJobIdRenderPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentsJobIdRenderPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


